mqtt:
  server: mqtt://192.168.66.10:1883
  servername: 192.168.66.10
  username: "huawei"
  password: "huawei"
  clientId: "gige_device_test"
  certification: ../res/client.crt
  privatekey: ../res/client.key
  caCert: ../res/ca.crt
http:
  certification: ../res/server.pem
  privatekey: ../res/server.key
  caCert: ""
configmap: ../res/configmap_test.json
